twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        score_service: '@App\Service\ScoreService'



when@test:
    twig:
        strict_variables: true
