controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

bentools_webpush:
    resource: '@WebPushBundle/Resources/config/routing.xml'
    prefix: /webpush